[2024-05-26T01:01:05.669+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:01:05.841+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: process_sales.read_send_data_task scheduled__2023-03-20T01:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-05-26T01:01:05.841334+00:00 and task will be retried at 2024-05-26T01:01:10.187686+00:00.
[2024-05-26T01:01:05.850+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
